### ISSUE TITLE
Result about xgaze and where I can find the paper.

### ISSUE THREAD

**Issue by RichardoMrMu** [bjj9/EVE_SCPT#1]
I see the representation on gaze 2021, and see this method's result on xgaze-dataset. Can I use this code directly to test on xgaze? Or there will have another code to release which can test on xgaze-dataset. And where can I find the paper an individual-difference-ware model for cross person gaze estimation. Thanks!

**Comment by bjj9** [comment]
Hi -- thank you for your feedback! We just uploaded the paper here: https://arxiv.org/abs/2106.14183. 
We didn't release the full code for testing XGaze in this repository, though the current code can be tested on the XGaze dataset provided point of gaze (PoG) on screen. Our code in this repository is based on the EVE repository where the conversion code between gaze direction and PoG is provided. For XGaze, this conversion process can be found in their paper and you'll need to work through it before applying our method.
